# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\"\x1e\n\x0bPeerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1d\n\x0cPeerResponse\x12\r\n\x05peers\x18\x01 \x03(\t\"\x11\n\x0fNodeInfoRequest\"H\n\x10NodeInfoResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrent_time\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xb2\x01\n\x0eNetworkService\x12+\n\x0cRegisterPeer\x12\x0c.PeerRequest\x1a\r.PeerResponse\x12\'\n\x08GetPeers\x12\x0c.PeerRequest\x1a\r.PeerResponse\x12\x32\n\x0bGetNodeInfo\x12\x10.NodeInfoRequest\x1a\x11.NodeInfoResponse\x12\x16\n\x04Ping\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEERREQUEST']._serialized_start=17
  _globals['_PEERREQUEST']._serialized_end=47
  _globals['_PEERRESPONSE']._serialized_start=49
  _globals['_PEERRESPONSE']._serialized_end=78
  _globals['_NODEINFOREQUEST']._serialized_start=80
  _globals['_NODEINFOREQUEST']._serialized_end=97
  _globals['_NODEINFORESPONSE']._serialized_start=99
  _globals['_NODEINFORESPONSE']._serialized_end=171
  _globals['_EMPTY']._serialized_start=173
  _globals['_EMPTY']._serialized_end=180
  _globals['_NETWORKSERVICE']._serialized_start=183
  _globals['_NETWORKSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
