# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\"5\n\x0fTransactionList\x12\"\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x0c.Transaction\"\x1e\n\x0bPeerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1d\n\x0cPeerResponse\x12\r\n\x05peers\x18\x01 \x03(\t\"\x11\n\x0fNodeInfoRequest\"L\n\x10PeerInfoResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06synced\x18\x02 \x01(\x08\x12\x17\n\x0f\x62lock_candidate\x18\x03 \x01(\t\"2\n\x0fTransactionHash\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\tfrom_host\x18\x02 \x01(\t\" \n\x0bTransaction\x12\x11\n\tjson_data\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xea\x02\n\x0eNetworkService\x12+\n\x0cRegisterPeer\x12\x0c.PeerRequest\x1a\r.PeerResponse\x12\'\n\x08GetPeers\x12\x0c.PeerRequest\x1a\r.PeerResponse\x12\x16\n\x04Ping\x12\x06.Empty\x1a\x06.Empty\x12(\n\x0bGetPeerInfo\x12\x06.Empty\x1a\x11.PeerInfoResponse\x12\x32\n\x18\x42roadcastTransactionHash\x12\x10.TransactionHash\x1a\x04.Ack\x12\x34\n\x12GetFullTransaction\x12\x10.TransactionHash\x1a\x0c.Transaction\x12$\n\x0e\x41\x64\x64Transaction\x12\x0c.Transaction\x1a\x04.Ack\x12\x30\n\x12GetAllTransactions\x12\x06.Empty\x1a\x10.TransactionList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONLIST']._serialized_start=17
  _globals['_TRANSACTIONLIST']._serialized_end=70
  _globals['_PEERREQUEST']._serialized_start=72
  _globals['_PEERREQUEST']._serialized_end=102
  _globals['_PEERRESPONSE']._serialized_start=104
  _globals['_PEERRESPONSE']._serialized_end=133
  _globals['_NODEINFOREQUEST']._serialized_start=135
  _globals['_NODEINFOREQUEST']._serialized_end=152
  _globals['_PEERINFORESPONSE']._serialized_start=154
  _globals['_PEERINFORESPONSE']._serialized_end=230
  _globals['_TRANSACTIONHASH']._serialized_start=232
  _globals['_TRANSACTIONHASH']._serialized_end=282
  _globals['_TRANSACTION']._serialized_start=284
  _globals['_TRANSACTION']._serialized_end=316
  _globals['_ACK']._serialized_start=318
  _globals['_ACK']._serialized_end=340
  _globals['_EMPTY']._serialized_start=342
  _globals['_EMPTY']._serialized_end=349
  _globals['_NETWORKSERVICE']._serialized_start=352
  _globals['_NETWORKSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
